package api

// Generated by https://quicktype.io
//
type NamespaceList struct {
	Namespaces []string `json:"namespaces"`
}

// Generated by https://quicktype.io

type PodList struct {
	Pods []string `json:"pods"`
}
